# Generated by Django 5.1 on 2025-01-16 14:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Table_One',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('state', models.BooleanField()),
                ('datetime_register', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Onetomany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('state', models.BooleanField()),
                ('datetime_register', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_table_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enerbit.test_table_one')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Manytomany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('datetime_register', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_table_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enerbit.test_table_one')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Table_Two',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('state', models.BooleanField()),
                ('datetime_register', models.DateTimeField(default=django.utils.timezone.now)),
                ('tableone', models.ManyToManyField(through='enerbit.Test_Manytomany', to='enerbit.test_table_one')),
            ],
        ),
        migrations.AddField(
            model_name='test_table_one',
            name='tabletwo',
            field=models.ManyToManyField(through='enerbit.Test_Manytomany', to='enerbit.test_table_two'),
        ),
        migrations.AddField(
            model_name='test_manytomany',
            name='test_table_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enerbit.test_table_two'),
        ),
    ]
